In [1]:
# This adds the path to import the development version (git repo) of NDI Python
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [2]:
from ndi import Experiment, Document
from ndi.database.sql import SQL as Database
from ndi.database.file_system import BinaryCollection
from ndi.query import Query as Q, AndQuery, OrQuery
from ndi.database.utils import print_everything_in, destroy_everything_in
from sqlalchemy import and_, or_
import struct

In [3]:
import numpy as np

In [4]:
# Create SQL database object passing in a connection string
db = Database('postgres://postgres:1Password!@localhost:5432/practice')
destroy_everything_in(db)

In [5]:
# Creating/connecting to a binary collection on disk providing a directory to store binary files and a name
bc = BinaryCollection('./test_db', name='demo')

In [6]:
# Creating experiment object and connecting it to database and binary collection
e = Experiment('test_experiment').connect(
    directory='../tests/data/intracell_example',
    database=db,
    binary_collection=bc
)

In [7]:
# Creating an NDI Document
doc = Document({'content': 'numpy array'}, name='numpy_doc', type_='with_bin')

# Adding NDI Document to experiment
e.add_document(doc)

In [8]:
# Opening a write stream object
ws = doc.binary.open_write_stream()

# Writing values into write stream object, write method only accepts bytes objects
for i in range(5):
    ws.write(struct.pack('d', i))
for i in reversed(range(11)):
    ws.write(struct.pack('d', i))

# Closing write stream object
ws.close()

In [9]:
# Opening a read stream object
rs = doc.binary.open_read_stream()

# Reading bytes data from read stream and converting into numpy array
print(np.frombuffer(rs.read(40)))
print(np.frombuffer(rs.read(32)))

# Getting position of pointer in the stream object
print(f'pointer at index {rs.tell()}')

# Reading the rest of read stream data and converting input numpy array
print(np.frombuffer(rs.read()))

# Closing read stream object
rs.close()

[0. 1. 2. 3. 4.]
[10.  9.  8.  7.]
pointer at index 72
[6. 5. 4. 3. 2. 1. 0.]


In [10]:
# Demo-ing write stream object using Pythonic "with"
with doc.binary.open_write_stream() as ws:
    for i in [3.425,4.34,5345,.453,542.,45]:
        ws.write(struct.pack('d', i))

In [11]:
# Demo-ing read stream object using Pythonic "with"
with doc.binary.open_read_stream() as rs:
    print(np.frombuffer(rs.read(-1)))

[3.425e+00 4.340e+00 5.345e+03 4.530e-01 5.420e+02 4.500e+01]


In [12]:
# Creating an NDI Document
doc = Document({'content': 'byte data'}, name='bytes_doc', type_='with_bin')

# Adding NDI Document to experiment
e.add_document(doc)

In [13]:
# Demo-ing write stream object using Pythonic "with"
with doc.binary.open_write_stream() as ws:
    ws.write(b'datadatadata')

In [14]:
# Demo-ing read stream object using Pythonic "with"
with doc.binary.open_read_stream() as rs:
    print(rs.read(-1).decode())

b'datadatadata'


In [15]:
destroy_everything_in(db)