In [1]:
# This adds the path to import the development version (git repo) of NDI Python
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [2]:
from ndi import Experiment, Document
from ndi.database.sql import SQL as Database
from ndi.database.file_system import BinaryCollection
from ndi.query import Query as Q, AndQuery, OrQuery
from ndi.database.utils import print_everything_in, destroy_everything_in
from sqlalchemy import and_, or_
import struct

In [3]:
import numpy as np

In [4]:
db = Database('postgres://postgres:1Password!@localhost:5432/practice')
destroy_everything_in(db)

In [5]:
bc = BinaryCollection('./test_db', name='demo')

In [6]:
e = Experiment('test_experiment').connect(
    database=db,
    binary_collection=bc
)

In [7]:
doc = Document({'hello': 'world'}, name='doc', type_='with_bin')
e.add_document(doc)

In [8]:
ws = doc.binary.open_write_stream()
for i in range(5):
    ws.write(struct.pack('d', i))
for i in reversed(range(11)):
    ws.write(struct.pack('d', i))
ws.close()

In [9]:
rs = doc.binary.open_read_stream()
print(np.frombuffer(rs.read(40)))
print(np.frombuffer(rs.read(32)))
print(f'pointer at index {rs.tell()}')
print(np.frombuffer(rs.read()))
rs.close()

[0. 1. 2. 3. 4.]
[10.  9.  8.  7.]
pointer at index 72
[6. 5. 4. 3. 2. 1. 0.]


In [10]:
with doc.binary.open_write_stream() as ws:
    for i in [3.425,4.34,5345,.453,542.,45]:
        ws.write(struct.pack('d', i))

In [11]:
with doc.binary.open_read_stream() as rs:
    print(np.frombuffer(rs.read(-1)))

[3.425e+00 4.340e+00 5.345e+03 4.530e-01 5.420e+02 4.500e+01]


In [12]:
destroy_everything_in(db)