In [1]:
# This adds the path to import the development version (git repo) of NDI Python
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [2]:
from ndi import Session, Document
from did import DID
from did.database import SQL
from did.query import Query as Q, AndQuery, OrQuery
from sqlalchemy import and_, or_
import struct

In [3]:
import numpy as np

In [4]:
# Connecting to SQL database, passing in connection string
database_driver = SQL(
    'postgres://postgres:password@localhost:5432/ndi_demo_binary_collection', 
    hard_reset_on_init = True,
    debug_mode = False,
    verbose_feedback = True,
)

In [5]:
# Creating/connecting to binary collection, passing in path and collection name
binary_collection_path = './example/binary_collections/Demo_Binary_Collection'

In [6]:
data_interface_database = DID(database_driver, binary_collection_path, auto_save=False)

In [7]:
# Creating a new Session object and connecting it to its context
session = Session('demo_api_core').connect(
    '../tests/data/intracell_example',
    data_interface_database,
    load_existing=False
)

In [8]:
# Creating an NDI Document
doc = Document(name='numpy_doc')

# Adding NDI Document to session
session.add_document(doc)

In [9]:
# Opening a write stream object
ws = doc.binary.open_write_stream('new_data')

# Writing values into write stream object, write method only accepts bytes objects
for i in range(5):
    ws.write(struct.pack('d', i))
for i in reversed(range(11)):
    ws.write(struct.pack('d', i))

# Closing write stream object
ws.close()

In [10]:
# Opening a read stream object
rs = doc.binary.open_read_stream('new_data')

# Reading bytes data from read stream and converting into numpy array
print(np.frombuffer(rs.read(40)))
print(np.frombuffer(rs.read(32)))

# Getting position of pointer in the stream object
print(f'pointer at index {rs.tell()}')

# Reading the rest of read stream data and converting input numpy array
print(np.frombuffer(rs.read()))

# Closing read stream object
rs.close()

[0. 1. 2. 3. 4.]
[10.  9.  8.  7.]
pointer at index 72
[6. 5. 4. 3. 2. 1. 0.]


In [11]:
# Demo-ing write stream object using Pythonic "with"
with doc.binary.open_write_stream('ctx_managed_data') as ws:
    for i in [3.425,4.34,5345,.453,542.,45]:
        ws.write(struct.pack('d', i))

TypeError: open_write_stream() missing 1 required positional argument: 'name'

In [ ]:
# Demo-ing read stream object using Pythonic "with"
with doc.binary.open_read_stream() as rs:
    print(np.frombuffer(rs.read(-1)))

In [ ]:
# Creating an NDI Document
doc = Document({'content': 'byte data'}, name='bytes_doc', type_='with_bin')

# Adding NDI Document to session
e.add_document(doc)

In [ ]:
# Demo-ing write stream object using Pythonic "with"
with doc.binary.open_write_stream() as ws:
    ws.write(b'datadatadata')

In [ ]:
# Demo-ing read stream object using Pythonic "with"
with doc.binary.open_read_stream() as rs:
    print(rs.read(-1).decode())

In [ ]:
destroy_everything_in(db)